### ISSUE TITLE
parkinson.org.il

### ISSUE THREAD

**Issue by EasyListHebrew** [easylist/EasyListHebrew#10]
_From @DMTsurel on August 26, 2014 14:45_

http://www.parkinson.org.il/ page has 3 blocked elements, namely
http://www.parkinson.org.il/RedirectBanner.asp?BannerID=22
http://www.parkinson.org.il/RedirectBanner.asp?BannerID=23
http://www.parkinson.org.il/RedirectBanner.asp?BannerID=24

Would you be able to unblock these? They are pretty important to visitors of the site.

_Copied from original issue: ABPIsrael/EasyListHebrew#11_

**Comment by EasyListHebrew** [comment]
_From @EasyListIsrael on August 27, 2014 7:38_

can't see the website i get http://www.parkinson.org.il/ErrorPage.asp

**Comment by EasyListHebrew** [comment]
_From @EasyListIsrael on August 27, 2014 9:42_

fixed

**Comment by EasyListHebrew** [comment]
_From @DMTsurel on August 27, 2014 12:36_

Great, thanks.

**Comment by DMTsurel** [comment]
The same problem occurs now, I'd be glad if you can fix it again.

**Comment by DMTsurel** [comment]
I see that you closed the issue. Is there a fix? Because the problem is still visible to me.

**Comment by EasyListHebrew** [comment]
This issue was moved to abpisrael/easylisthebrew#10
